---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: tsung-master
  name: tsung-master
spec:
  # clusterIP: None # modify
  selector:
    run: tsung-master
  ports:
  - port: 8091
    nodePort: 31865 # modify
  sessionAffinity: None
  # type: ClusterIP
  type: NodePort # modify
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tsung-master
spec:
  serviceName: "tsung-master"
  replicas: 1
  selector:
    matchLabels:
      run: tsung-master
  template:
    metadata:
      labels:
        run: tsung-master
    spec:
      containers:
      - name: tsung
        image: ddragosd/tsung-docker:1.6.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ERL_SSH_PORT
          value: "22"
        args:
        - -k
        - -f
        - /tsung/config.xml
        - -F
        - start
        volumeMounts:
        - mountPath: /tsung
          name: config-volume
      volumes:
      - configMap:
          name: tsung-config
        name: config-volume
